version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - ~/docker/volumes/mongodb:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DATABASE}"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    env_file: .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SMTP_PORT}:${SMTP_PORT}"
